M48
; DRILL file {KiCad 7.0.7} date Tue May 14 17:55:07 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-14T17:55:07+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.780
%
G90
G05
T1
X149.352Y-69.078
X149.352Y-84.318
X189.992Y-69.078
X189.992Y-84.318
T0
M30
